clang-tidy: remove/mark unused const
Address -Wunused-const-variable by deleting the unused
systemd1UnitBasePath constant. This silences the warning under -Werror.
No functional changes.

Fixed below error
'''
../src/srvcfg_manager.cpp:46:30: error: unused variable 'systemd1UnitBasePath' [-Werror,-Wunused-const-variable]
   46 | static constexpr const char* systemd1UnitBasePath =
      |                              ^~~~~~~~~~~~~~~~~~~~
'''

Change-Id: I0f9bbbb355ab12eaa1f094f40f513646ebfb55a8
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>